### ISSUE TITLE
First parameter of 'evaluate' fails if it is not numeric

### ISSUE THREAD

**Issue by AngryBOSS** [JordanMatuschka/grossmaul#26]
Regression - previously it was possible to evaluate single keywords with '!evaluate $noun'
Current output is the last entry into the database

Example: 
>evaluate $noun
>remember kids - hippies are bad people pretending to be good, and punks are good people pretending to be bad
>evaluate 1959
>On May 23, 1967, a solar storm jammed radar, radio, and ballistic missile early warning systems, leading the US to start prepping for war before discovering the cause was the sun, and not the Russians.

**Comment by JordanMatuschka** [comment]
Fixed in 26-first-parameter-of-evaluate-fails-if-it-is-not-numeric
